language: go
services:
  - docker
go:
  - "1.14"
env:
  - "GO15VENDOREXPERIMENT=1"
before_install:
  - make deps
script:
  - make multiarch-build test-coverage
after_success:

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
